(function(root){
'use strict';
const LIMITS={tasks:120,budget:100,risks:80,assumptions:80,decisions:80};
function fresh(){return {bookmarks:[],savedSearches:[],tasks:[],budget:[],currency:'USD',contingency:10,risks:[],assumptions:[],decisions:[],comparison:{ids:[],weights:[3,3,2,2],ratings:{}},display:{contrast:false,fontSize:100,spacing:false,focus:false},widgets:['next','progress','review','saved']};}
function ok(x,m){if(!x)throw Error(m);}
function text(x,max=800){ok(typeof x==='string'&&x.length<=max,'Invalid or oversized workspace text');return x;}
function num(x,min,max){ok(Number.isFinite(x)&&x>=min&&x<=max,'Workspace number out of range');return x;}
function date(x){x=text(x??'',10);ok(x===''||(/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x),'Invalid calendar date');return x;}
function array(x,max){ok(Array.isArray(x)&&x.length<=max,'Workspace list exceeds its limit');return x;}
function id(x){x=text(x,100);ok(/^[a-zA-Z0-9_-]+$/.test(x),'Invalid workspace ID');return x;}
function select(x,choices){ok(choices.includes(x),'Unknown workspace choice');return x;}
const roles=['Caregiver','Educator','NGO practitioner','Youth ally','Legal advocate','Community leader','Policymaker','Journalist','Researcher'];
function validate(input,catalog){const x=input??{},out=fresh(),valid=catalog.strategies.map(s=>s.id),types=['todo','doing','blocked','done'];
 out.bookmarks=[...new Set(array(x.bookmarks??[],100).map(v=>select(v,valid)))];
 out.savedSearches=[...new Set(array(x.savedSearches??[],20).map(v=>text(v,120)))];
 out.tasks=array(x.tasks??[],LIMITS.tasks).map(t=>({id:id(t.id),title:text(t.title,160),strategy:select(t.strategy??'',['',...valid]),owner:select(t.owner??'NGO practitioner',roles),due:date(t.due),status:select(t.status??'todo',types),depends:array(t.depends??[],120).map(id),repeat:select(t.repeat??'none',['none','weekly','monthly']),note:text(t.note??'',800)}));
 const ids=out.tasks.map(t=>t.id);ok(new Set(ids).size===ids.length,'Duplicate task IDs');out.tasks.forEach(t=>{ok(t.depends.every(d=>ids.includes(d)&&d!==t.id),'Unknown or self dependency');t.depends=[...new Set(t.depends)];});
 const visiting=new Set(),done=new Set();function visit(key){if(done.has(key))return;ok(!visiting.has(key),'Task dependencies contain a cycle');visiting.add(key);out.tasks.find(t=>t.id===key).depends.forEach(visit);visiting.delete(key);done.add(key);}ids.forEach(visit);
 out.tasks.forEach(t=>ok(t.status!=='done'||t.depends.every(d=>out.tasks.find(q=>q.id===d).status==='done'),'Complete prerequisite tasks first'));
 out.budget=array(x.budget??[],LIMITS.budget).map(b=>({id:id(b.id),label:text(b.label,160),category:select(b.category,['Training','Supervision','Accessibility','Transport','Materials','Referral capacity','Evaluation','Other']),quantity:num(b.quantity,0,1000000),unitCost:num(b.unitCost,0,100000000)}));
 out.currency=select(x.currency??'USD',['USD','EUR','KES','UGX','TZS','ZAR','GHS','NGN','XOF','MAD']);out.contingency=num(x.contingency??10,0,100);
 out.risks=array(x.risks??[],LIMITS.risks).map(r=>({id:id(r.id),title:text(r.title,160),likelihood:num(r.likelihood,1,5),impact:num(r.impact,1,5),mitigation:text(r.mitigation),owner:select(r.owner,roles),status:select(r.status,['open','mitigating','reviewed']),review:date(r.review)}));
 out.assumptions=array(x.assumptions??[],LIMITS.assumptions).map(a=>({id:id(a.id),text:text(a.text),check:text(a.check),status:select(a.status,['untested','supported','challenged']),review:date(a.review)}));
 out.decisions=array(x.decisions??[],LIMITS.decisions).map(d=>({id:id(d.id),title:text(d.title,160),rationale:text(d.rationale),reversibility:select(d.reversibility,['reversible','costly to reverse','specialist review required']),review:date(d.review),outcome:text(d.outcome??'')}));
 for(const k of ['budget','risks','assumptions','decisions'])ok(new Set(out[k].map(x=>x.id)).size===out[k].length,'Duplicate workspace record IDs');
 const co=x.comparison??{};out.comparison.ids=[...new Set(array(co.ids??[],4).map(v=>select(v,valid)))];out.comparison.weights=array(co.weights??[3,3,2,2],4).map(v=>num(v,0,5));ok(out.comparison.weights.length===4,'Expected four comparison weights');
 for(const sid of out.comparison.ids){const rr=co.ratings?.[sid]??[0,0,0,0];out.comparison.ratings[sid]=array(rr,4).map(v=>num(v,0,5));ok(rr.length===4,'Expected four comparison ratings');}
 const p=x.display??{};out.display={contrast:p.contrast===true,fontSize:num(p.fontSize??100,90,150),spacing:p.spacing===true,focus:p.focus===true};out.widgets=[...new Set(array(x.widgets??out.widgets,4).map(v=>select(v,['next','progress','review','saved'])))];return out;
}
function blockers(task,tasks){return task.depends.filter(id=>tasks.find(t=>t.id===id)?.status!=='done');}
function budget(work){const base=work.budget.reduce((sum,b)=>sum+b.quantity*b.unitCost,0);return {base,contingency:base*work.contingency/100,total:base*(1+work.contingency/100)};}
function scores(comp){const total=comp.weights.reduce((a,b)=>a+b,0);return comp.ids.map(id=>({id,score:total?comp.weights.reduce((sum,w,i)=>sum+w*(comp.ratings[id]?.[i]??0),0)/total:null}));}
function nextDate(value,repeat){const d=new Date(value+'T12:00:00Z');if(Number.isNaN(+d))return '';if(repeat==='weekly')d.setUTCDate(d.getUTCDate()+7);else if(repeat==='monthly'){const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));}return d.toISOString().slice(0,10);}
function csv(rows){const cell=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return rows.map(r=>r.map(cell).join(',')).join('\r\n');}
function personalWarnings(value){const t=JSON.stringify(value);return [/@[a-z0-9.-]+\.[a-z]{2,}/i.test(t)?'Possible email address':null,/(?:\+\d[\d ()-]{7,}\d)/.test(t)?'Possible phone number':null,/\b(?:passport|national id|date of birth|full name|home address)\b/i.test(t)?'Possible identifying-data phrase':null].filter(Boolean);}
function ics(tasks){const esc=s=>String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Safeguard Africa//Planning//EN','CALSCALE:GREGORIAN'];for(const t of tasks.filter(x=>x.due)){lines.push('BEGIN:VEVENT','UID:'+t.id+'@safeguard.local','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z/,'Z'),'DTSTART;VALUE=DATE:'+t.due.replaceAll('-',''),'SUMMARY:'+esc(t.title),'DESCRIPTION:Programme planning reminder. Verify local safety before action.','END:VEVENT');}lines.push('END:VCALENDAR');return lines.map(line=>{let parts=[],part='',bytes=0;for(const c of line){const n=new TextEncoder().encode(c).length;if(bytes+n>73){parts.push(part);part=' ';bytes=1;}part+=c;bytes+=n;}parts.push(part);return parts.join('\r\n');}).join('\r\n')+'\r\n';}
async function encrypt(value,password){ok(typeof password==='string'&&password.length>=12,'Use a passphrase of at least 12 characters');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const keyMaterial=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},keyMaterial,{name:'AES-GCM',length:256},false,['encrypt']);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(value)));const b64=a=>btoa(Array.from(new Uint8Array(a),v=>String.fromCharCode(v)).join(''));return {format:'safeguard-encrypted',version:1,algorithm:'AES-GCM',kdf:'PBKDF2-SHA256',iterations:250000,salt:b64(salt),iv:b64(iv),ciphertext:b64(cipher)};}
async function decrypt(box,password){ok(box?.format==='safeguard-encrypted'&&box.version===1&&box.algorithm==='AES-GCM'&&box.kdf==='PBKDF2-SHA256'&&box.iterations===250000,'Unsupported encrypted backup');const decode=s=>{text(s,1500000);return Uint8Array.from(atob(s),c=>c.charCodeAt(0));};const salt=decode(box.salt),iv=decode(box.iv),cipher=decode(box.ciphertext);ok(salt.length===16&&iv.length===12,'Invalid encryption parameters');const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);try{return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher)));}catch{throw Error('Could not decrypt: wrong passphrase or damaged file');}}
const api={fresh,validate,blockers,budget,scores,nextDate,csv,ics,personalWarnings,encrypt,decrypt};root.SG_WORK=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
