const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
require('../modules/workspace-core.js');
const root=path.join(__dirname,'..'),D=JSON.parse(fs.readFileSync(path.join(root,'data/catalog.json'))),C=require('../modules/core.js');let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name,e);process.exitCode=1;}}
test('catalogue counts and unique IDs',()=>{for(const k of ['strategies','sources','claims','infrastructures','guides'])assert.equal(new Set(D[k].map(x=>x.id)).size,D[k].length);assert.equal(D.strategies.length,36);});
test('every strategy has complete execution fields',()=>D.strategies.forEach(s=>{for(const k of ['goal','failure','stop','metric','review'])assert.ok(s[k].length>20);assert.ok(s.steps.length>=4);assert.ok(s.pre.length);assert.equal(s.kind,'Inference');}));
test('all strategy citations resolve',()=>D.strategies.forEach(s=>s.refs.forEach(id=>assert.ok(D.sources.some(x=>x.id===id),id))));
test('all strategy infrastructure links resolve',()=>D.strategies.forEach(s=>s.links.forEach(id=>assert.ok(D.infrastructures.some(x=>x.id===id),id))));
test('all claims resolve to sources',()=>D.claims.forEach(c=>assert.ok(D.sources.some(s=>s.id===c.source))));
test('all infrastructure references resolve',()=>D.infrastructures.forEach(i=>i.refs.forEach(id=>assert.ok(D.sources.some(s=>s.id===id)))));
test('source URLs HTTPS and caveats present',()=>D.sources.forEach(s=>{assert.match(s.url,/^https:\/\//);assert.ok(s.limit);assert.ok(s.checked);}));
test('fresh state roundtrip',()=>assert.deepEqual(C.parseImport(JSON.stringify(C.fresh()),D).plan,[]));
test('v1 migration',()=>assert.deepEqual(C.migrate({schema:1,selected:['S03']},D).plan,['S03']));
test('v2 migration',()=>assert.equal(C.migrate({schema:2,plan:['S01']},D).schema,4));
test('future schema rejected',()=>assert.throws(()=>C.migrate({schema:5},D)));
test('negative schema rejected',()=>assert.throws(()=>C.migrate({schema:-1},D)));
test('malformed JSON rejected',()=>assert.throws(()=>C.parseImport('{',D)));
test('oversized import rejected',()=>assert.throws(()=>C.parseImport(' '.repeat(1000001),D)));
test('unknown strategy rejected',()=>assert.throws(()=>C.migrate({schema:3,plan:['fake']},D)));
test('duplicate strategy deduplicated',()=>assert.deepEqual(C.migrate({schema:3,plan:['S01','S01']},D).plan,['S01']));
test('oversized notes rejected',()=>assert.throws(()=>C.migrate({schema:3,notes:'x'.repeat(4001)},D)));
test('unknown role rejected',()=>assert.throws(()=>C.migrate({schema:3,role:'surveillance'},D)));
test('unrecognised task fields dropped',()=>assert.deepEqual(C.migrate({schema:3,tasks:{'S01:0':true,'evil':true}},D).tasks,{'S01:0':true}));
test('XSS text escaped',()=>assert.equal(C.escape('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));
test('prototype pollution ignored',()=>{C.parseImport('{"schema":3,"__proto__":{"polluted":true}}',D);assert.equal({}.polluted,undefined);});
test('invalid source protocol rejected',()=>assert.throws(()=>C.migrate({schema:3,ledger:[{url:'javascript:alert(1)'}]},D)));
test('valid user research remains unverified',()=>{const s=C.migrate({schema:3,ledger:[{title:'Example',url:'https://example.org',finding:'Test',limit:'Unreviewed'}]},D);assert.equal(s.ledger[0].kind,'User-entered / unverified');});
test('metric numerator cannot exceed denominator',()=>assert.throws(()=>C.migrate({schema:3,metrics:[{type:'Access',period:'2026-09',n:11,d:10}]},D)));
test('metric denominator under ten rejected',()=>assert.throws(()=>C.migrate({schema:3,metrics:[{type:'Access',period:'2026-09',n:4,d:5}]},D)));
test('metric invalid month rejected',()=>assert.throws(()=>C.migrate({schema:3,metrics:[{type:'Access',period:'2026-99',n:5,d:10}]},D)));
test('valid aggregate accepted',()=>assert.equal(C.migrate({schema:3,metrics:[{type:'Access',period:'2026-09',n:24,d:30}]},D).metrics[0].n,24));
test('readiness cannot certify empty plan',()=>{const s=C.fresh();s.gates=[...C.GATES];assert.equal(C.progress(s,D).canReview,false);});
test('progress counts only selected steps and is reversible',()=>{const s=C.fresh();s.plan=['S01'];s.tasks={'S01:0':true,'S02:0':true};assert.equal(C.progress(s,D).xp,10);s.tasks['S01:0']=false;assert.equal(C.progress(s,D).xp,0);});
test('snapshot excludes all local sensitive fields',()=>{const s=C.fresh();s.notes='PRIVATE';s.metrics=[{n:7}];s.ledger=[{finding:'PRIVATE'}];s.tasks={'S01:0':true};s.plan=['S01'];const snap=C.snapshot(s);assert.equal(JSON.stringify(snap).includes('PRIVATE'),false);for(const k of ['notes','metrics','ledger','gates','tasks','role'])assert.equal(k in snap,false);});
test('protocol mismatch rejected',()=>assert.throws(()=>C.validateMessage({...C.snapshot(C.fresh()),protocol:99},D)));
test('peer future schema rejected',()=>assert.throws(()=>C.validateMessage({...C.snapshot(C.fresh()),schema:99},D)));
test('unknown peer IDs rejected',()=>assert.throws(()=>C.validateMessage({...C.snapshot(C.fresh()),plan:['bad']},D)));
test('peer snapshot strips extra fields',()=>{const v=C.validateMessage({...C.snapshot(C.fresh()),notes:'PRIVATE'},D);assert.equal(v.notes,undefined);});
test('hello validation',()=>assert.equal(C.validateMessage({app:'safeguard-africa',protocol:1,schema:4,type:'hello'},D).type,'hello'));
test('deterministic guide preserves stop and citations',()=>{const g=C.guide(D.strategies[0]);assert.ok(g.includes(D.strategies[0].stop));assert.ok(g.includes('CHARTER'));});
test('all JavaScript parses',()=>{for(const dir of ['modules','data'])for(const f of fs.readdirSync(path.join(root,dir)).filter(x=>x.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(root,dir,f),'utf8'),{filename:f});new vm.Script(fs.readFileSync(path.join(root,'sw.js'),'utf8'));});
test('manifest supports project subpath',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest')));assert.equal(m.scope,'./');assert.equal(m.start_url,'./index.html#home');m.icons.forEach(i=>assert.ok(fs.existsSync(path.join(root,i.src))));});
test('sample backups validate',()=>{for(const f of ['sample-backup.json','sample-v1.json'])C.parseImport(fs.readFileSync(path.join(root,'data',f),'utf8'),D);});
console.log(`${passed} tests passed`);
