const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const W=require('../modules/workspace-core.js'),C=require('../modules/core.js'),D=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/catalog.json')));let passed=0;
async function test(name,fn){try{await fn();console.log('PASS '+name);passed++;}catch(error){console.error('FAIL '+name,error);process.exitCode=1;}}
const task=(id,depends=[])=>({id,title:'Fictional task '+id,owner:'Educator',strategy:'S03',due:'2026-09-30',status:'todo',depends,repeat:'none',note:''});
(async()=>{
await test('schema 3 migrates without losing plan/notes',()=>{const s=C.migrate({schema:3,plan:['S03'],notes:'Fictional programme'},D);assert.equal(s.schema,4);assert.equal(s.notes,'Fictional programme');assert.deepEqual(s.workspace.tasks,[]);});
await test('workspace full roundtrip',()=>assert.deepEqual(W.validate(W.fresh(),D),W.fresh()));
await test('future schema rejected',()=>assert.throws(()=>C.migrate({schema:5},D)));
await test('valid dependency chain',()=>{const w=W.validate({...W.fresh(),tasks:[task('a'),task('b',['a'])]},D);assert.deepEqual(W.blockers(w.tasks[1],w.tasks),['a']);});
await test('dependency cycle rejected',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[task('a',['b']),task('b',['a'])]},D),/cycle/));
await test('unknown dependency rejected',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[task('a',['missing'])]},D)));
await test('self dependency rejected',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[task('a',['a'])]},D)));
await test('duplicate task IDs rejected',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[task('a'),task('a')]},D)));
await test('completion blocked by unfinished prerequisite',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[task('a'),{...task('b',['a']),status:'done'}]},D),/prerequisite/));
await test('completed dependency chain accepted',()=>assert.equal(W.validate({...W.fresh(),tasks:[{...task('a'),status:'done'},{...task('b',['a']),status:'done'}]},D).tasks[1].status,'done'));
await test('reopening completed prerequisite rejected when dependents done',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[{...task('a'),status:'todo'},{...task('b',['a']),status:'done'}]},D)));
await test('calendar invalid date rejected',()=>assert.throws(()=>W.validate({...W.fresh(),tasks:[{...task('a'),due:'2026-02-30'}]},D)));
await test('monthly recurrence clamps end of month',()=>assert.equal(W.nextDate('2026-01-31','monthly'),'2026-02-28'));
await test('weekly recurrence crosses year',()=>assert.equal(W.nextDate('2026-12-29','weekly'),'2027-01-05'));
await test('negative budget inputs rejected',()=>assert.throws(()=>W.validate({...W.fresh(),budget:[{id:'a',label:'Test',category:'Training',quantity:-1,unitCost:20}]},D)));
await test('budget arithmetic',()=>assert.ok(Math.abs(W.budget({...W.fresh(),budget:[{quantity:4,unitCost:25}],contingency:10}).total-110)<1e-9));
await test('weighted score transparent',()=>assert.equal(W.scores({ids:['S03'],weights:[3,1,0,0],ratings:{S03:[4,2,1,1]}})[0].score,3.5));
await test('zero weights do not fabricate score',()=>assert.equal(W.scores({ids:['S03'],weights:[0,0,0,0],ratings:{S03:[5,5,5,5]}})[0].score,null));
await test('fifth comparison option rejected',()=>assert.throws(()=>W.validate({...W.fresh(),comparison:{ids:['S01','S02','S03','S04','S05']}},D)));
await test('CSV spreadsheet formula injection neutralised',()=>{const t=W.csv([['=1+1','+SUM(A1)','@x','-1','normal']]);assert.match(t,/"'=1\+1"/);assert.match(t,/"'@x"/);});
await test('CSV quotes/newlines preserved',()=>assert.equal(W.csv([['say "yes"','a\nb']]),'"say ""yes""","a\nb"'));
await test('iCalendar only emits dated tasks with escaped punctuation',()=>{const t=W.ics([{...task('a'),title:'Meeting; review, yes'},{...task('b'),due:''}]);assert.equal((t.match(/BEGIN:VEVENT/g)||[]).length,1);assert.match(t,/DTSTART;VALUE=DATE:20260930/);assert.match(t,/Meeting\\; review\\, yes/);});
await test('long unicode calendar lines folded within byte limit',()=>{for(const line of W.ics([{...task('a'),title:'é'.repeat(160)}]).split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);});
await test('identifier scan labels patterns not certainty',()=>assert.equal(W.personalWarnings('person@example.org +254 700 123 456').length,2));
await test('new workspace excluded from peer snapshots',()=>{const s=C.fresh();s.workspace.risks=[{title:'PRIVATE'}];assert.equal(JSON.stringify(C.snapshot(s)).includes('PRIVATE'),false);});
await test('unknown workspace fields stripped',()=>assert.equal(W.validate({...W.fresh(),identities:['PRIVATE']},D).identities,undefined));
await test('workspace data survives exported backup migration',()=>{const s=C.fresh();s.workspace.tasks=[task('a')];assert.equal(C.parseImport(JSON.stringify(s),D).workspace.tasks[0].id,'a');});
await test('encrypted backup roundtrip',async()=>{const s=C.fresh();s.plan=['S03'];const box=await W.encrypt(s,'test passphrase only');assert.equal(box.algorithm,'AES-GCM');assert.deepEqual(await W.decrypt(box,'test passphrase only'),s);});
await test('encryption uses random salts and IVs',async()=>{const a=await W.encrypt({x:1},'test passphrase only'),b=await W.encrypt({x:1},'test passphrase only');assert.notEqual(a.salt,b.salt);assert.notEqual(a.iv,b.iv);assert.notEqual(a.ciphertext,b.ciphertext);});
await test('wrong passphrase rejected',async()=>{const box=await W.encrypt({x:1},'test passphrase only');await assert.rejects(W.decrypt(box,'wrong passphrase'),/Could not decrypt/);});
await test('ciphertext modification rejected',async()=>{const box=await W.encrypt({x:1},'test passphrase only');box.ciphertext=(box.ciphertext[0]==='A'?'B':'A')+box.ciphertext.slice(1);await assert.rejects(W.decrypt(box,'test passphrase only'));});
await test('short passphrase rejected',async()=>await assert.rejects(W.encrypt({},'short')));
await test('unsupported encryption parameters rejected',async()=>await assert.rejects(W.decrypt({format:'safeguard-encrypted',version:1,iterations:1},'test passphrase only')));
console.log(passed+' workspace tests passed');
})();
