/* Dependency-free Chromium integration tests. Uses a fresh profile outside the release folder. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),output=process.env.SG_TEST_OUTPUT||path.join(root,'..','qa-output');fs.mkdirSync(output,{recursive:true});
const browser=process.env.SG_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe';
const profile=path.join(output,'browser-profile');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.md':'text/plain'};
const server=http.createServer((req,res)=>{try{let u=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(u.startsWith('/project/'))u=u.slice(8);if(u.endsWith('/'))u+='index.html';const file=path.resolve(root,'.'+u);if(!file.startsWith(root+path.sep))throw Error();res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'text/plain','Cache-Control':'no-cache'});res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end('Missing');}});
const results=[],errors=[],requests=[];let proc,cdp;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function connect(url){const ws=new WebSocket(url);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});let i=0;const pending=new Map();ws.onmessage=ev=>{const m=JSON.parse(ev.data);if(m.id){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Network.requestWillBeSent')requests.push(m.params.request.url);};return {send(method,params={}){return new Promise((resolve,reject)=>{const id=++i;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(Error('CDP timeout '+method));}},15000).unref();});},close:()=>ws.close()};}
async function evalJS(expression,client=cdp){const r=await client.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text+' '+r.exceptionDetails.exception?.description);return r.result.value;}
async function waitFor(expression,client=cdp){for(let i=0;i<100;i++){try{if(await evalJS(expression,client))return;}catch{}await sleep(100);}throw Error('Wait timed out: '+expression);}
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+': '+e.message);}}
async function route(name){await evalJS(`location.hash=${JSON.stringify(name)}`);await sleep(100);}
async function click(selector){await evalJS(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(100);}
async function run(){await new Promise(r=>server.listen(8765,'127.0.0.1',r));proc=spawn(browser,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-port=9223','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:'ignore'});let tabs;for(let i=0;i<100;i++){try{tabs=await (await fetch('http://127.0.0.1:9223/json/list')).json();if(tabs.length)break;}catch{}await sleep(100);}if(!tabs?.length)throw Error('Browser did not start');cdp=await connect(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await cdp.send('Runtime.enable');await cdp.send('Page.enable');await cdp.send('Network.enable');await cdp.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await cdp.send('Page.navigate',{url:'http://127.0.0.1:8765/project/index.html'});await waitFor('!!globalThis.SG_APP');
await test('loads at GitHub Pages-like project subpath',async()=>{assert.match(await evalJS('document.querySelector("h1").textContent'),/safer next step/);assert.equal(await evalJS('SG_STORE.mode()'),'IndexedDB');});
await test('splash dismisses without trapping the page',async()=>{await sleep(1500);assert.equal(await evalJS('!!document.getElementById("splash")'),false);});
await test('all 16 registry routes render and share navigation',async()=>{const ids=await evalJS('SG_ROUTES.map(x=>x.id)');for(const id of ids){await route(id);assert.ok(await evalJS('document.querySelector("main h1")?.textContent'));assert.equal(await evalJS('document.querySelector("#sidenav [aria-current=page]").getAttribute("href")'),'#'+id);}});
await test('whole-catalogue search finds documentation strategy',async()=>{await evalJS('document.querySelector("#search").value="birth registration";document.querySelector("#search").dispatchEvent(new Event("input",{bubbles:true}))');await sleep(300);assert.match(await evalJS('document.querySelector("main").textContent'),/Navigate birth registration barriers/);});
await test('add strategy resets gates and creates execution plan',async()=>{await route('strategies/S03');await click('[data-action="toggle-plan"][data-value="S03"]');await route('plan');assert.deepEqual(await evalJS('SG_APP.getState().plan'),['S03']);assert.equal(await evalJS('document.querySelectorAll("[data-task]").length'),4);});
await test('completion and XP are reversible',async()=>{await click('[data-task="S03:0"]');assert.equal(await evalJS('SG_CORE.progress(SG_APP.getState(),SG_DATA).xp'),10);await click('[data-task="S03:0"]');assert.equal(await evalJS('SG_CORE.progress(SG_APP.getState(),SG_DATA).xp'),0);});
await test('readiness gates require all acknowledgements',async()=>{await click('[data-action="review-plan"]');assert.match(await evalJS('document.querySelector("#modalbody").textContent'),/incomplete/);await evalJS('document.querySelector("#modal").close()');await evalJS('document.querySelectorAll("[data-gate]").forEach(x=>x.click())');await sleep(200);assert.equal(await evalJS('SG_CORE.progress(SG_APP.getState(),SG_DATA).canReview'),true);});
await test('notes and state survive reload',async()=>{await evalJS('document.querySelector("#plan-notes").value="FICTIONAL QA programme note";document.querySelector("#plan-notes").dispatchEvent(new Event("change",{bubbles:true}))');await sleep(200);await cdp.send('Page.reload');await waitFor('!!globalThis.SG_APP');assert.equal(await evalJS('SG_APP.getState().notes'),'FICTIONAL QA programme note');assert.equal(await evalJS('SG_APP.getState().gates.length'),4);});
await test('safely renders hostile note content',async()=>{await evalJS('document.querySelector("#plan-notes").value="<img src=x onerror=globalThis.pwned=true>";document.querySelector("#plan-notes").dispatchEvent(new Event("change",{bubbles:true}))');await sleep(200);await route('home');await route('plan');assert.equal(await evalJS('globalThis.pwned===true'),false);assert.equal(await evalJS('document.querySelector("#plan-notes").value'),'<img src=x onerror=globalThis.pwned=true>');});
await test('IndexedDB backup and retrieval',async()=>{const b=await evalJS('(async()=>{const s=SG_APP.getState();await SG_STORE.backup(s);const keys=await SG_STORE.list();return {count:keys.length,plan:(await SG_STORE.get(keys.at(-1))).plan};})()');assert.ok(b.count>0);assert.deepEqual(b.plan,['S03']);});
await test('aggregate monitoring form works',async()=>{await route('monitor');await evalJS('document.querySelector("#metric-period").value="2026-09";document.querySelector("#metric-n").value=24;document.querySelector("#metric-d").value=30;document.querySelector("[name=safe]").checked=true;document.querySelector("#metric-form").requestSubmit()');await sleep(200);assert.match(await evalJS('document.querySelector("main").textContent'),/80.0%/);});
await test('research form preserves user-entered distinction',async()=>{await route('research');await evalJS('document.querySelector("#ledger-title").value="Example review";document.querySelector("#ledger-url").value="https://example.org";document.querySelector("#ledger-date").value="Unknown";document.querySelector("#ledger-design").value="Example";document.querySelector("#ledger-scope").value="Fictional";document.querySelector("#ledger-finding").value="Test only";document.querySelector("#ledger-limit").value="Unverified";document.querySelector("#ledger-form").requestSubmit()');await sleep(200);assert.equal(await evalJS('SG_APP.getState().ledger.at(-1).kind'),'User-entered / unverified');});
await test('deterministic assistant works without runtime/network',async()=>{await route('assistant');await click('[data-action="deterministic"]');assert.match(await evalJS('document.querySelector("#assistant-output").textContent'),/Stop rule/);assert.equal(requests.some(u=>u.includes('esm.sh')),false);});
await test('theme and engagement controls persist',async()=>{await route('settings');await evalJS('document.querySelector("#theme").value="dark";document.querySelector("#theme").dispatchEvent(new Event("change",{bubbles:true}));document.querySelector("[data-setting=engagement]").click()');await sleep(200);assert.equal(await evalJS('document.body.dataset.theme'),'dark');await route('plan');assert.equal(await evalJS('document.querySelector(".constellation")'),null);await route('settings');await evalJS('document.querySelector("#theme").value="light";document.querySelector("#theme").dispatchEvent(new Event("change",{bubbles:true}))');await sleep(100);});
await test('same-origin local-tab sharing requires explicit snapshot',async()=>{
 const target=await cdp.send('Target.createTarget',{url:'http://127.0.0.1:8765/project/index.html#collaborate'});const list=await (await fetch('http://127.0.0.1:9223/json/list')).json();const other=await connect(list.find(x=>x.id===target.targetId).webSocketDebuggerUrl);await other.send('Runtime.enable');await waitFor('!!globalThis.SG_APP',other);
 await evalJS('globalThis.received=[];SG_OPTIONAL.join("local","testroom1234567890","",m=>received.push(m),()=>{})',other);
 await evalJS('SG_OPTIONAL.join("local","testroom1234567890","",()=>{},()=>{})');await sleep(100);assert.equal(await evalJS('received.length',other),0);
 await evalJS('SG_OPTIONAL.share(SG_CORE.snapshot(SG_APP.getState()))');await sleep(200);assert.equal(await evalJS('received.length',other),1);assert.equal(await evalJS('"notes" in received[0]',other),false);assert.deepEqual(await evalJS('received[0].plan',other),['S03']);
 await evalJS('SG_OPTIONAL.leave()',other);await evalJS('SG_OPTIONAL.leave()');other.close();await cdp.send('Target.closeTarget',{targetId:target.targetId});
});
await test('core service worker installs and controls subpath',async()=>{await waitFor('!!navigator.serviceWorker.controller');const cached=await evalJS('(async()=>{const ks=await caches.keys();const k=ks.find(x=>x.startsWith("safeguard-africa-"));return {key:k,count:(await (await caches.open(k)).keys()).length};})()');assert.ok(cached.count>=25);assert.ok(cached.key.includes(encodeURIComponent('http://127.0.0.1:8765/project/')));});
await test('cold document reload and navigation work offline',async()=>{await cdp.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await cdp.send('Page.reload');await waitFor('!!globalThis.SG_APP');await route('strategies');assert.equal(await evalJS('document.querySelectorAll("main details").length'),36);await route('research');assert.equal(await evalJS('document.querySelectorAll(".source-card").length'),27);await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});});
await test('mobile routes have no horizontal page overflow',async()=>{await cdp.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});for(const id of ['home','plan','evidence','collaborate','settings','infrastructure']){await route(id);assert.ok(await evalJS('document.documentElement.scrollWidth<=innerWidth+1'),id);}await route('home');await click('#menu');assert.equal(await evalJS('document.querySelector("#menu").getAttribute("aria-expanded")'),'true');await click('#sidenav a[href="#strategies"]');assert.equal(await evalJS('document.querySelector("#menu").getAttribute("aria-expanded")'),'false');});
await route('home');fs.writeFileSync(path.join(output,'mobile.png'),Buffer.from((await cdp.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
await cdp.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await route('home');await sleep(100);fs.writeFileSync(path.join(output,'desktop.png'),Buffer.from((await cdp.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
await test('no third-party requests during core workflow',async()=>{assert.deepEqual(requests.filter(u=>u.startsWith('http')&&!u.startsWith('http://127.0.0.1:8765')),[]);});
await test('no uncaught browser exceptions',async()=>assert.deepEqual(errors,[]));
}
run().catch(e=>{console.error(e);results.push({name:'Harness',status:'FAIL',error:e.message});}).finally(async()=>{fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({date:new Date().toISOString(),results,errors,requests:[...new Set(requests)]},null,2));try{await cdp?.send('Browser.close');}catch{}cdp?.close();proc?.kill();server.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;console.log(`${results.filter(r=>r.status==='PASS').length} browser tests passed; ${results.filter(r=>r.status==='FAIL').length} failed`);});
